---
- name: install server, stuff and wordpress
  hosts: vbmachines
  become: yes
  vars_files:
    - vars/mysql_settings.yml
    - vars/adminer_settings.yml
    - vars/php_settings.yml
  roles:
    - role: geerlingguy.repo-epel
    - role: geerlingguy.repo-remi
    - role: geerlingguy.apache
    - role: geerlingguy.php
    - role: geerlingguy.mysql
    - role: geerlingguy.php-mysql
    - role: geerlingguy.adminer
    - role: wordpress
...