---
- name: install server, stuff and wordpress
  hosts: vbmachines
  sudo: yes
  vars:
    wordpress_path: ""
    wordpress_database_name: wordpress
  vars_files:
    - vars/mysql_settings.yml
    - vars/adminer_settings.yml
    - vars/php_settings.yml
  roles:
    - role: geerlingguy.repo-epel
    - role: geerlingguy.repo-remi
    - role: geerlingguy.apache
    - role: geerlingguy.php
    - role: geerlingguy.php-mysql
    - role: geerlingguy.adminer
    - role: setup_mysql
    - role: download_and_unzip_wp
  # - { role: configurate_wp }
...