---
- name: install server, stuff and wordpress
  hosts: vbmachines
  sudo: yes
  vars:
    wordpress_path: ""
    php_enablerepo: "remi-php70,epel"
    php_packages_state: "latest"
    php_packages_extra: ["php-mysqlnd"]
  vars_files:
   - vars/wp_settings.yml
  roles:
  - { role: geerlingguy.repo-epel }
  - { role: geerlingguy.repo-remi }
  - { role: httpd }
  - { role: geerlingguy.php }
  - { role: download_and_unzip_wp }
  # - { role: configurate_wp }