---
- name: Создание базы данных с именем {{ wordpress_database_name }}
  mysql_db:
    name: "{{ wordpress_database_name }}"
    state: present
  notify: restart apache
- name: Создание пользователя {{ mysql_username }} с паролем [ДАННЫЕ УДАЛЕНЫ] и полным доступом к базе данных {{ wordpress_database_name }}
  mysql_user:
    name: "{{ mysql_username }}"
    password: "{{ mysql_password }}"
    priv: '{{ wordpress_database_name }}.*:ALL'
    state: present
  notify: restart apache
...