- handlers:
  name: restart apache
  service:
    name: httpd
    state: restarted
- tasks:
  name: install apache
  yum:
    name: httpd
    state: latest
  notify: restart apache
  name: Enable service httpd
  service:
    name: httpd
    enabled: yes
  notify: restart apache